import os
print('[+] Tool Created By Nguyen Quang Hung')
print('[+] Download GoLang from Golang.org/dl/')
try:
    os.system('python3 -m pip install wheel')
    os.system('python -m pip install wheel')
    os.system('pip3 install wheel')
    os.system('py -m pip install wheel')
    os.system('python3 -m pip install pyfiglet')
    os.system('pip3 install pyfiglet')
    os.system('py -m pip install pyfiglet')
    os.system('python -m pip install pyfiglet')
    os.system('python3 -m pip install pyttsx3')
    os.system('pip3 install pyttsx3')
    os.system('py -m pip install pyttsx3')
    os.system('python -m pip install pyttsx3')
    os.system('python3 -m pip install colorama')
    os.system('pip3 install colorama')
    os.system('py -m pip install colorama')
    os.system('python -m pip install colorama')
    os.system('sudo apt-get install figlet')
    print('[+] SUCCESSFUL')
except:
    print('[+] SUCCESSFUL')
